language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-5
            - libboost1.55-all-dev
            - libhdf5-serial-dev
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - CMAKE_C_COMPILER=gcc-5
        - CMAKE_CXX_COMPILER=g++-5

    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-5
            - libboost1.55-all-dev
            - libhdf5-serial-dev
      env:
        - CMAKE_BUILD_TYPE=RELEASE
        - CMAKE_C_COMPILER=gcc-5
        - CMAKE_CXX_COMPILER=g++-5

    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-6
            - libboost1.55-all-dev
            - libhdf5-serial-dev
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - CMAKE_C_COMPILER=gcc-6
        - CMAKE_CXX_COMPILER=g++-6

    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-6
            - libboost1.55-all-dev
            - libhdf5-serial-dev
      env:
        - CMAKE_BUILD_TYPE=RELEASE
        - CMAKE_C_COMPILER=gcc-6
        - CMAKE_CXX_COMPILER=g++-6

    - os: osx
      osx_image: xcode7.3
      compiler: clang++
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - CMAKE_C_COMPILER=clang-3.7
        - CMAKE_CXX_COMPILER=clang++-3.7

    - os: osx
      osx_image: xcode7.3
      compiler: clang++
      env:
        - CMAKE_BUILD_TYPE=RELEASE
        - CMAKE_C_COMPILER=clang-3.7
        - CMAKE_CXX_COMPILER=clang++-3.7

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew tap homebrew/science;
      brew update;
      brew install hdf5 --enable-cxx;
      brew install llvm37;
      brew outdated boost || brew upgrade boost;
    fi

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER} -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} ..

script:
  - make -j
  - make test
