language: cpp

sudo: false

matrix:
  include:
    - os: linux
      compiler: clang++
      addons:
        apt:
          sources:
            - boost-latest
            - george-edison55-precise-backports
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - clang-3.7
            - libboost1.55-all-dev
            - libhdf5-serial-dev
      env: CMAKE_BUILD_TYPE=DEBUG

    - os: linux
      compiler: clang++
      addons:
        apt:
          sources:
            - boost-latest
            - george-edison55-precise-backports
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - clang-3.7
            - libboost1.55-all-dev
            - libhdf5-serial-dev
      env: CMAKE_BUILD_TYPE=RELEASE

    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - boost-latest
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-5
            - libboost1.55-all-dev
            - libhdf5-serial-dev
      env: CMAKE_BUILD_TYPE=DEBUG

    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - boost-latest
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-5
            - libboost1.55-all-dev
            - libhdf5-serial-dev
      env: CMAKE_BUILD_TYPE=RELEASE

    - os: osx
      osx_image: xcode7.3
      compiler: clang++
      env: CMAKE_BUILD_TYPE=DEBUG

    - os: osx
      osx_image: xcode7.3
      compiler: clang++
      env: CMAKE_BUILD_TYPE=RELEASE

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew tap homebrew/science;
      brew update;
      brew install hdf5 --enable-cxx;
      brew install llvm37;
      brew outdated boost || brew upgrade boost;
    fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ "$CXX" = "clang++" ]; then
        export CXX=clang++-3.7 CC=clang-3.7;
      elif [ "$CXX" = "g++" ]; then
        export CXX=g++-5 CC=gcc-5;
      fi;
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export CXX=clang++-3.7 CC=clang-3.7;
    fi

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..

script:
  - make
  - make test
